// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYsJhxKv_v9b702W_QCYoQLTwIjLoeW9M',
    appId: '1:1048460634076:web:aff583bdc2bd5d108a9119',
    messagingSenderId: '1048460634076',
    projectId: 'traditionalgems-4e869',
    authDomain: 'traditionalgems-4e869.firebaseapp.com',
    storageBucket: 'traditionalgems-4e869.firebasestorage.app',
    measurementId: 'G-5G6TTKG519',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6ju8rniN5pxQ4n0Qq97fWdDJyPDyvwKU',
    appId: '1:1048460634076:android:a04b72699174bd208a9119',
    messagingSenderId: '1048460634076',
    projectId: 'traditionalgems-4e869',
    storageBucket: 'traditionalgems-4e869.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3x1cM3_hELD5NJsLCFhQ2ujwcjurob6A',
    appId: '1:1048460634076:ios:3054279d488a2de08a9119',
    messagingSenderId: '1048460634076',
    projectId: 'traditionalgems-4e869',
    storageBucket: 'traditionalgems-4e869.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3x1cM3_hELD5NJsLCFhQ2ujwcjurob6A',
    appId: '1:1048460634076:ios:3054279d488a2de08a9119',
    messagingSenderId: '1048460634076',
    projectId: 'traditionalgems-4e869',
    storageBucket: 'traditionalgems-4e869.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYsJhxKv_v9b702W_QCYoQLTwIjLoeW9M',
    appId: '1:1048460634076:web:d9b44a805c13aabc8a9119',
    messagingSenderId: '1048460634076',
    projectId: 'traditionalgems-4e869',
    authDomain: 'traditionalgems-4e869.firebaseapp.com',
    storageBucket: 'traditionalgems-4e869.firebasestorage.app',
    measurementId: 'G-3CB2JDBMW8',
  );
}
